"""add is_active and category

Revision ID: 33103ba22e45
Revises: bca50fc31a8d
Create Date: 2025-01-25 23:19:16.104104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33103ba22e45'
down_revision = 'bca50fc31a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
